/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{
   uint32_t *pRCC_AHBENR = (uint32_t *)0x40023830;
   *pRCC_AHBENR |= (1<<0);

   uint32_t *pGPIOA_MODER = (uint32_t *)0x40020000;
   *pGPIOA_MODER &= ~(3 << 10);
   *pGPIOA_MODER |= (1 << 10);

   uint32_t *pGPIOA_ODR = (uint32_t *)0x40020014;
   *pGPIOA_ODR |= (1 << 5);

   while(1){

	   *pGPIOA_ODR ^= (1 << 5);

	   for(uint32_t i = 0; i<500000; i++){}

   }

}
