/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define STK_CSR ((uint32_t *)0xE000E010) //SysTick control and status register
#define STK_RVR ((uint32_t *)0xE000E014) //SysTick reload value register
#define STK_CVR ((uint32_t *)0xE000E018) //SysTick current value register

uint32_t *pGPIOA_ODR = (uint32_t *)0x40020014;


int mode_state(int m){

	if(m == 0){
		*pGPIOA_ODR &= ~(1 << 5);
	}
	else if(m == 1){

		*pGPIOA_ODR ^= (1 << 5);
		for(volatile uint32_t i = 0; i < 400000; i++);
	}
	else if(m == 2){

		*pGPIOA_ODR ^= (1 << 5);
		for(volatile uint32_t i = 0; i < 200000; i++);
	}
	else if(m == 3){

			*pGPIOA_ODR ^= (1 << 5);
			for(volatile uint32_t i = 0; i < 100000; i++);
		}
}


int main(void)
{
	/*
	 * CHALLENGE 1: BLINK LED
	 *
   uint32_t *pRCC_AHBENR = (uint32_t *)0x40023830;
   *pRCC_AHBENR |= (1<<0);

   uint32_t *pGPIOA_MODER = (uint32_t *)0x40020000;
   *pGPIOA_MODER &= ~(3 << 10);
   *pGPIOA_MODER |= (1 << 10);

   uint32_t *pGPIOA_ODR = (uint32_t *)0x40020014;
   *pGPIOA_ODR |= (1 << 5);

   while(1){

	   *pGPIOA_ODR ^= (1 << 5);

	   for(uint32_t i = 0; i<500000; i++){}

   }
	*/



	/*CHALLENGE 2: REGISTER INPUT POLL*/
	uint32_t *pRCC_AHB1ENR = (uint32_t *)0x40023830;
	*pRCC_AHB1ENR |= (1 << 0) | (1 << 2);

	// LED ON
	   uint32_t *pGPIOA_MODER = (uint32_t *)0x40020000;
	   *pGPIOA_MODER &= ~(3 << 10);
	   *pGPIOA_MODER |= (1 << 10);


	   *pGPIOA_ODR |= (0 << 5);
	//

	uint32_t *pGPIOC_IDR = (uint32_t *)0x40020810; // POINTER TO BUTTON ADDRESS

	/*
	while(1){
		if(!(*pGPIOC_IDR & (1 << 13)))
		{
			*pGPIOA_ODR |= (1 << 5);
		}
		else *pGPIOA_ODR &= ~(1 << 5);

	}*/

	/*
	 * CHALLENGE 3: TOGGLE COMMAND
	 *
	uint8_t last_button_state = 1;

	while(1)
	{
		uint8_t current_button_state = (*pGPIOC_IDR & (1 << 13))? 1:0;

		if( last_button_state == 1 && current_button_state == 0){

			*pGPIOA_ODR ^= (1 << 5);

			for(volatile uint32_t i = 0; i < 50000; i++);
		}


		last_button_state = current_button_state;

	}*/

	/* CHALLENGE 4: LED TOGGLE SPEED CONTROLLER*/

	uint8_t last_button_state = 1;
	uint8_t mode = 0;

	while(1)
		{
	uint8_t current_button_state = (*pGPIOC_IDR & (1 << 13))? 1:0;

	if( last_button_state == 1 && current_button_state == 0){

		 mode = (mode + 1) % 4;

		for(volatile uint32_t i = 0; i < 40000; i++);
	}

	mode_state(mode);

	last_button_state = current_button_state;
		}


}
